module.exports =
	"en":
		CONFIG_COMMAND_ERROR: "The \"configure\" command only supports changing one setting at a time in the form of \"<setting name> <setting value>\" or reading a single setting in the form of \"<setting name>\""
		CONFIG_ACCESS_ERROR: "You are not permitted to use the \"configure\" command."
		CONFIG_KEY_SAVED: "Setting saved successfully."
		CONFIG_INVALID_KEY: "The provided setting name is not valid."
		CONFIG_INVALID_VALUE: "The provided setting value is not valid."
		GENERAL_USAGE_ERROR: "Please check documentation on how to correctly use the Gunsmith."	
		NO_PLATFORM_PROVIDED_ERROR: "You must specify your gaming platform or have the admin set the default platform."
		NO_USERNAME_PROVIDED_ERROR: "You must specify your Xbox Gamertag, Playstation Online ID, or Battle.net ID in either your request or as your name in your Slack profile."	
		USERNAME_NOT_FOUND_ERROR: "Could not find a user with that name on the specified network."
		NO_CHARACTERS_FOUND_ERROR: "No characters were found for the specified player."
		NO_CLASS_FOUND_ERROR: "You have specified a class, however you have no characters of that class."
		DUPLICATE_CLASS_ERROR: "You specified a class, however you have multiple characters of that class." 
		ITEM_NOT_FOUND_ERROR: "Unable to find the specified item for this character."	
		API_ERROR: "The Gunsmith Bot could not communicate properly with the Bungie API. Please let the admin know."
		MANIFEST_UPDATE_STARTED: "The manifest is being updated. Please wait."
		MANIFEST_UPDATE_COMPLETE: "The manifest has been updated to the latest version."
		HELP_TITLE: "Using the Gunsmith Bot"
		HELP_TEXT: "To show off your items, @ the bot with your username, class, network, and item slot, separated by spaces.\nIf no class is specified, the bot will always look at the most recently played class.\nIf you've set up your slack profile so that your *first name* matches your username, you can omit it.\nIf your gamertag only exists on one network, that can be omitted as well."
	
	"fr":
		CONFIG_COMMAND_ERROR: "La commande \"configure\" prend uniquement en charge la définition d'une seule variable d'environnement à la fois sous la forme \"<nom de la variable> <valeur de la variable>\"."
		CONFIG_ACCESS_ERROR: "Vous n'êtes pas autorisé à utiliser la commande \"configure\""
		CONFIG_KEY_SAVED: "Setting saved successfully."
		CONFIG_INVALID_KEY: "Le nom de variable fourni n'est pas valide."
		CONFIG_INVALID_VALUE: "The provided variable value is not valid."
		GENERAL_USAGE_ERROR: "S'il vous plaît vérifier la documentation sur la façon d'utiliser correctement le Armurier."	
		NO_PLATFORM_PROVIDED_ERROR: "You must specify your gaming platform or have the admin set the default platform."
		NO_USERNAME_PROVIDED_ERROR: "Vous devez spécifier votre identifiant Xbox Gamertag, votre identifiant Playstation Online ou votre identifiant Battle.net dans votre demande ou sous votre nom dans votre profil Slack."	
		USERNAME_NOT_FOUND_ERROR: "Impossible de trouver un utilisateur portant ce nom sur le réseau spécifié."
		NO_CHARACTERS_FOUND_ERROR: "Aucun personnage n'a été trouvé pour le joueur spécifié."
		NO_CLASS_FOUND_ERROR: "Vous avez spécifié une classe, mais vous n'avez aucun personnage de cette classe."
		DUPLICATE_CLASS_ERROR: "Vous avez spécifié une classe, mais vous en avez plusieurs caractères." 
		ITEM_NOT_FOUND_ERROR: "Impossible de trouver l'élément spécifié pour ce personnage."	
		API_ERROR: "The Gunsmith Bot could not communicate properly with the Bungie API. Please let the admin know."
		MANIFEST_UPDATE_STARTED: "The manifest is being updated. Please wait."
		MANIFEST_UPDATE_COMPLETE: "Le manifeste a été mis à jour à la dernière version."
		HELP_TITLE: "Utiliser le Bot Armurier"
		HELP_TEXT: "Pour afficher vos éléments, @le bot avec votre nom d'utilisateur, votre classe, votre réseau et votre emplacement, séparés par des espaces.\nSi aucune classe n'est spécifiée, le bot regardera toujours la dernière classe jouée.\nSi vous avez configuré votre profil de manière à ce que votre * prénom * corresponde à votre nom d'utilisateur, vous pouvez l'omettre.\nSi votre nom d'utilisateur n'existe que sur un réseau, vous pouvez également l'omettre."

	"es":
		CONFIG_COMMAND_ERROR: "The \"configure\" command only supports setting a single environment variable at a time in the form of \"<variable name> <variable value>\"."
		CONFIG_ACCESS_ERROR: "You are not permitted to use the \"configure\" command"
		CONFIG_KEY_SAVED: "Setting saved successfully."
		CONFIG_INVALID_KEY: "The provided variable name is not valid."
		CONFIG_INVALID_VALUE: "The provided variable value is not valid."
		GENERAL_USAGE_ERROR: "Please check documentation on how to correctly use the Gunsmith."
		NO_PLATFORM_PROVIDED_ERROR: "You must specify your gaming platform or have the admin set the default platform."
		NO_USERNAME_PROVIDED_ERROR: "You must specify your Xbox Gamertag, Playstation Online ID, or Battle.net ID in either your request or as your name in your Slack profile."	
		USERNAME_NOT_FOUND_ERROR: "Could not find a user with that name on the specified network."
		NO_CHARACTERS_FOUND_ERROR: "No characters were found for the specified player."
		NO_CLASS_FOUND_ERROR: "You have specified a class, however you have no characters of that class."
		DUPLICATE_CLASS_ERROR: "You specified a class, however you have multiple characters of that class." 
		ITEM_NOT_FOUND_ERROR: "Unable to find the specified item for this character."	
		API_ERROR: "The Gunsmith Bot could not communicate properly with the Bungie API. Please let the admin know."
		MANIFEST_UPDATE_STARTED: "The manifest is being updated. Please wait."
		MANIFEST_UPDATE_COMPLETE: "The manifest has been updated to the latest version."
		HELP_TITLE: "Using the Gunsmith Bot"
		HELP_TEXT: "To show off your items, @ the bot with your username, class, network, and item slot, separated by spaces.\nIf no class is specified, the bot will always look at the most recently played class.\nIf you've set up your slack profile so that your *first name* matches your username, you can omit it.\nIf your gamertag only exists on one network, that can be omitted as well."
	
	"de":
		CONFIG_COMMAND_ERROR: "The \"configure\" command only supports setting a single environment variable at a time in the form of \"<variable name> <variable value>\"."
		CONFIG_ACCESS_ERROR: "You are not permitted to use the \"configure\" command"
		CONFIG_KEY_SAVED: "Setting saved successfully."
		CONFIG_INVALID_KEY: "The provided variable name is not valid."
		CONFIG_INVALID_VALUE: "The provided variable value is not valid."
		GENERAL_USAGE_ERROR: "Please check documentation on how to correctly use the Gunsmith."
		NO_PLATFORM_PROVIDED_ERROR: "You must specify your gaming platform or have the admin set the default platform."
		NO_USERNAME_PROVIDED_ERROR: "You must specify your Xbox Gamertag, Playstation Online ID, or Battle.net ID in either your request or as your name in your Slack profile."	
		USERNAME_NOT_FOUND_ERROR: "Could not find a user with that name on the specified network."
		NO_CHARACTERS_FOUND_ERROR: "No characters were found for the specified player."
		NO_CLASS_FOUND_ERROR: "You have specified a class, however you have no characters of that class."
		DUPLICATE_CLASS_ERROR: "You specified a class, however you have multiple characters of that class." 
		ITEM_NOT_FOUND_ERROR: "Unable to find the specified item for this character."	
		API_ERROR: "The Gunsmith Bot could not communicate properly with the Bungie API. Please let the admin know."
		MANIFEST_UPDATE_STARTED: "The manifest is being updated. Please wait."
		MANIFEST_UPDATE_COMPLETE: "The manifest has been updated to the latest version."
		HELP_TITLE: "Using the Gunsmith Bot"
		HELP_TEXT: "To show off your items, @ the bot with your username, class, network, and item slot, separated by spaces.\nIf no class is specified, the bot will always look at the most recently played class.\nIf you've set up your slack profile so that your *first name* matches your username, you can omit it.\nIf your gamertag only exists on one network, that can be omitted as well."
	
	"it":
		CONFIG_COMMAND_ERROR: "The \"configure\" command only supports setting a single environment variable at a time in the form of \"<variable name> <variable value>\"."
		CONFIG_ACCESS_ERROR: "You are not permitted to use the \"configure\" command"
		CONFIG_KEY_SAVED: "Setting saved successfully."
		CONFIG_INVALID_KEY: "The provided variable name is not valid."
		CONFIG_INVALID_VALUE: "The provided variable value is not valid."
		GENERAL_USAGE_ERROR: "Please check documentation on how to correctly use the Gunsmith."
		NO_PLATFORM_PROVIDED_ERROR: "You must specify your gaming platform or have the admin set the default platform."
		NO_USERNAME_PROVIDED_ERROR: "You must specify your Xbox Gamertag, Playstation Online ID, or Battle.net ID in either your request or as your name in your Slack profile."	
		USERNAME_NOT_FOUND_ERROR: "Could not find a user with that name on the specified network."
		NO_CHARACTERS_FOUND_ERROR: "No characters were found for the specified player."
		NO_CLASS_FOUND_ERROR: "You have specified a class, however you have no characters of that class."
		DUPLICATE_CLASS_ERROR: "You specified a class, however you have multiple characters of that class." 
		ITEM_NOT_FOUND_ERROR: "Unable to find the specified item for this character."	
		API_ERROR: "The Gunsmith Bot could not communicate properly with the Bungie API. Please let the admin know."
		MANIFEST_UPDATE_STARTED: "The manifest is being updated. Please wait."
		MANIFEST_UPDATE_COMPLETE: "The manifest has been updated to the latest version."
		HELP_TITLE: "Using the Gunsmith Bot"
		HELP_TEXT: "To show off your items, @ the bot with your username, class, network, and item slot, separated by spaces.\nIf no class is specified, the bot will always look at the most recently played class.\nIf you've set up your slack profile so that your *first name* matches your username, you can omit it.\nIf your gamertag only exists on one network, that can be omitted as well."
	
	"ja":
		CONFIG_COMMAND_ERROR: "\"configure\"コマンドは、一度に1つの環境変数を \"変数名変数値\"の形式で設定することのみをサポートしています。"
		CONFIG_ACCESS_ERROR: "\"configure\"コマンドを使用することはできません"
		CONFIG_KEY_SAVED: "Setting saved successfully."
		CONFIG_INVALID_KEY: "指定された変数名は無効です。"
		CONFIG_INVALID_VALUE: "The provided variable value is not valid."
		GENERAL_USAGE_ERROR: "ガンスミスを正しく使用する方法についてのドキュメントを確認してください。"
		NO_PLATFORM_PROVIDED_ERROR: "You must specify your gaming platform or have the admin set the default platform."
		NO_USERNAME_PROVIDED_ERROR: "Xbox Gamertag、Playstation Online ID、またはBattle.net IDは、あなたのリクエストまたはあなたのスラックプロファイルのあなたの名前で指定する必要があります。"	
		USERNAME_NOT_FOUND_ERROR: "指定されたネットワーク上でその名前のユーザーを見つけることができませんでした。"
		NO_CHARACTERS_FOUND_ERROR: "指定したプレーヤーの文字が見つかりませんでした。"
		NO_CLASS_FOUND_ERROR: "クラスを指定しましたが、そのクラスの文字はありません。"
		DUPLICATE_CLASS_ERROR: "クラスを指定しましたが、そのクラスの複数の文字があります。" 
		ITEM_NOT_FOUND_ERROR: "この文字の指定された項目を見つけることができません。"	
		API_ERROR: "gunsmithボットはBungie APIと適切に通信できませんでした。 管理者に知らせてください。"
		MANIFEST_UPDATE_STARTED: "The manifest is being updated. Please wait."
		MANIFEST_UPDATE_COMPLETE: "マニフェストは最新バージョンに更新されました。"
		HELP_TITLE: "gunsmithボットの使用"
		HELP_TEXT: "あなたのアイテムを見せるために、@あなたのユーザ名、クラス、ネットワーク、アイテムスロットをスペースで区切ったボット。\nクラスが指定されていない場合、ボットは常に最近再生されたクラスを見ます。\nあなたの*名前*があなたのユーザ名と一致するようにあなたのスラックプロファイルを上げてください、あなたは省略することができます。\nあなたのゲーマータグが1つのネットワーク上にのみ存在する場合、省略することもできます。"
	
	"pt-br":
		CONFIG_COMMAND_ERROR: "The \"configure\" command only supports setting a single environment variable at a time in the form of \"<variable name> <variable value>\"."
		CONFIG_ACCESS_ERROR: "You are not permitted to use the \"configure\" command"
		CONFIG_KEY_SAVED: "Setting saved successfully."
		CONFIG_INVALID_KEY: "The provided variable name is not valid."
		CONFIG_INVALID_VALUE: "The provided variable value is not valid."
		GENERAL_USAGE_ERROR: "Please check documentation on how to correctly use the Gunsmith."
		NO_PLATFORM_PROVIDED_ERROR: "You must specify your gaming platform or have the admin set the default platform."
		NO_USERNAME_PROVIDED_ERROR: "You must specify your Xbox Gamertag, Playstation Online ID, or Battle.net ID in either your request or as your name in your Slack profile."	
		USERNAME_NOT_FOUND_ERROR: "Could not find a user with that name on the specified network."
		NO_CHARACTERS_FOUND_ERROR: "No characters were found for the specified player."
		NO_CLASS_FOUND_ERROR: "You have specified a class, however you have no characters of that class."
		DUPLICATE_CLASS_ERROR: "You specified a class, however you have multiple characters of that class." 
		ITEM_NOT_FOUND_ERROR: "Unable to find the specified item for this character."	
		API_ERROR: "The Gunsmith Bot could not communicate properly with the Bungie API. Please let the admin know."
		MANIFEST_UPDATE_STARTED: "The manifest is being updated. Please wait."
		MANIFEST_UPDATE_COMPLETE: "The manifest has been updated to the latest version."
		HELP_TITLE: "Using the Gunsmith Bot"
		HELP_TEXT: "To show off your items, @ the bot with your username, class, network, and item slot, separated by spaces.\nIf no class is specified, the bot will always look at the most recently played class.\nIf you've set up your slack profile so that your *first name* matches your username, you can omit it.\nIf your gamertag only exists on one network, that can be omitted as well."
	
	"es-mx":
		CONFIG_COMMAND_ERROR: "The \"configure\" command only supports setting a single environment variable at a time in the form of \"<variable name> <variable value>\"."
		CONFIG_ACCESS_ERROR: "You are not permitted to use the \"configure\" command."
		CONFIG_KEY_SAVED: "Setting saved successfully."
		CONFIG_INVALID_KEY: "The provided variable name is not valid."
		CONFIG_INVALID_VALUE: "The provided variable value is not valid."
		GENERAL_USAGE_ERROR: "Please check documentation on how to correctly use the Gunsmith."
		NO_PLATFORM_PROVIDED_ERROR: "You must specify your gaming platform or have the admin set the default platform."
		NO_USERNAME_PROVIDED_ERROR: "You must specify your Xbox Gamertag, Playstation Online ID, or Battle.net ID in either your request or as your name in your Slack profile."	
		USERNAME_NOT_FOUND_ERROR: "Could not find a user with that name on the specified network."
		NO_CHARACTERS_FOUND_ERROR: "No characters were found for the specified player."
		NO_CLASS_FOUND_ERROR: "You have specified a class, however you have no characters of that class."
		DUPLICATE_CLASS_ERROR: "You specified a class, however you have multiple characters of that class." 
		ITEM_NOT_FOUND_ERROR: "Unable to find the specified item for this character."	
		API_ERROR: "The Gunsmith Bot could not communicate properly with the Bungie API. Please let the admin know."
		MANIFEST_UPDATE_STARTED: "The manifest is being updated. Please wait."
		MANIFEST_UPDATE_COMPLETE: "The manifest has been updated to the latest version."
		HELP_TITLE: "Using the Gunsmith Bot"
		HELP_TEXT: "To show off your items, @ the bot with your username, class, network, and item slot, separated by spaces.\nIf no class is specified, the bot will always look at the most recently played class.\nIf you've set up your slack profile so that your *first name* matches your username, you can omit it.\nIf your gamertag only exists on one network, that can be omitted as well."
	
	"ru":
		CONFIG_COMMAND_ERROR: "Команда \"configure\" поддерживает только установку одной переменной среды за раз в форме \"<имя переменной> <значение переменной>\"."
		CONFIG_ACCESS_ERROR: "Вам не разрешается использовать команду \"configure\"."
		CONFIG_KEY_SAVED: "Setting saved successfully."
		CONFIG_INVALID_KEY: "Указанное имя переменной недопустимо."
		CONFIG_INVALID_VALUE: "The provided variable value is not valid."
		GENERAL_USAGE_ERROR: "Пожалуйста, проверьте документацию о том, как правильно использовать оружейный мастер."
		NO_PLATFORM_PROVIDED_ERROR: "You must specify your gaming platform or have the admin set the default platform."
		NO_USERNAME_PROVIDED_ERROR: "Вы должны указать свой Xbox Gamertag, Playstation Online ID или Battle.net ID в своем запросе или в качестве своего имени в профиле Slack."	
		USERNAME_NOT_FOUND_ERROR: "Не удалось найти пользователя с таким именем в указанной сети."
		NO_CHARACTERS_FOUND_ERROR: "Для указанного игрока не найдено ни одного символа."
		NO_CLASS_FOUND_ERROR: "Вы указали класс, однако у вас нет символов этого класса."
		DUPLICATE_CLASS_ERROR: "Вы указали класс, однако у вас есть несколько символов этого класса." 
		ITEM_NOT_FOUND_ERROR: "Не удалось найти указанный элемент для этого символа."	
		API_ERROR: "Брандмауэр не мог нормально общаться с API Bungie. Пожалуйста, сообщите администратору."
		MANIFEST_UPDATE_STARTED: "The manifest is being updated. Please wait."
		MANIFEST_UPDATE_COMPLETE: "Манифест обновлен до последней версии."
		HELP_TITLE: "Использование оружейного бота"
		HELP_TEXT: "Чтобы показать свои предметы, @ бот с вашим именем пользователя, класса, сети и слота элемента, разделенных пробелами.\nЕсли класс не указан, @ бот всегда будет смотреть на последний раз играемый класс.\nЕсли вы настроили свой профиль Slack, чтобы ваше *имя* совпало с вашим именем пользователя, вы можете его опустить.\nЕсли ваш игровой сервер существует только в одной сети, это также можно опустить."
	
	"pl":
		CONFIG_COMMAND_ERROR: "Polecenie \"configure\" obsługuje tylko pojedyncze ustawienia zmiennej środowiskowej w postaci \"<nazwa zmiennej> <wartość zmiennej>\"."
		CONFIG_ACCESS_ERROR: "Nie możesz używać polecenia \"configure\""
		CONFIG_KEY_SAVED: "Setting saved successfully."
		CONFIG_INVALID_KEY: "Podana nazwa zmiennej jest nieprawidłowa."
		CONFIG_INVALID_VALUE: "The provided variable value is not valid."
		GENERAL_USAGE_ERROR: "Proszę sprawdzić dokumentację, jak prawidłowo korzystać z Gunsmith."
		NO_PLATFORM_PROVIDED_ERROR: "You must specify your gaming platform or have the admin set the default platform."
		NO_USERNAME_PROVIDED_ERROR: "Musisz podać swój Xbox Gamertag, identyfikator Playstation Online lub ID Battle.net w swoim żądaniu lub jako swoje nazwisko w profilu Slack."	
		USERNAME_NOT_FOUND_ERROR: "Nie można znaleźć użytkownika o tej nazwie w określonej sieci."
		NO_CHARACTERS_FOUND_ERROR: "Nie znaleziono żadnych znaków dla określonego gracza."
		NO_CLASS_FOUND_ERROR: "Podałeś klasę, ale nie masz żadnych postaci z tej klasy."
		DUPLICATE_CLASS_ERROR: "Podałeś klasę, ale masz wiele postaci z tej klasy." 
		ITEM_NOT_FOUND_ERROR: "Nie można znaleźć określonego elementu dla tego znaku."	
		API_ERROR: "Robot rusznika nie mógł poprawnie komunikować się z interfejsem API Bungie. Powiadom administratora."
		MANIFEST_UPDATE_STARTED: "The manifest is being updated. Please wait."
		MANIFEST_UPDATE_COMPLETE: "Plik manifestu został zaktualizowany do najnowszej wersji."
		HELP_TITLE: "Korzystanie z bota rusznikarza"
		HELP_TEXT: "Aby pokazać swoje przedmioty, @ bot z nazwą użytkownika, klasą, siecią i pozycją, oddzielone spacjami.\nJeśli żadna klasa nie zostanie określona, bot zawsze będzie patrzył na ostatnio zagraną klasę.\nJeśli skonfigurowałeś Zmniejsz profil, aby twoje * imię * pasowało do Twojej nazwy użytkownika, możesz je pominąć.\nJeśli Twój tag gracza istnieje tylko w jednej sieci, możesz go również pominąć."
	
	"zh-cht":
		CONFIG_COMMAND_ERROR: "\“configure\”命令僅支持以“<變量名> <變量值>”的形式一次設置單個環境變量"
		CONFIG_ACCESS_ERROR: "您不能使用\“configure\”命令"
		CONFIG_KEY_SAVED: "Setting saved successfully."
		CONFIG_INVALID_KEY: "提供的變量名稱無效"
		CONFIG_INVALID_VALUE: "The provided variable value is not valid."
		GENERAL_USAGE_ERROR: "請查看有關如何正確使用槍械製造商的文件"
		NO_PLATFORM_PROVIDED_ERROR: "You must specify your gaming platform or have the admin set the default platform."
		NO_USERNAME_PROVIDED_ERROR: "您必須在您的請求中指定您的Xbox Gamertag，Playstation Online ID或Battle.net ID，或在您的Slack配置文件中指定您的名字"	
		USERNAME_NOT_FOUND_ERROR: "在指定的網絡上找不到具有該名稱的用戶"
		NO_CHARACTERS_FOUND_ERROR: "未找到指定播放器的字符"
		NO_CLASS_FOUND_ERROR: "您已指定了一個類，但是您沒有該類的字符"
		DUPLICATE_CLASS_ERROR: "您指定了一個類，但是您有該類的多個字符" 
		ITEM_NOT_FOUND_ERROR: "無法找到此角色的指定項目"	
		API_ERROR: "槍械機器人無法與Bungie API正確通信 請讓管理員知道"
		MANIFEST_UPDATE_STARTED: "The manifest is being updated. Please wait."
		MANIFEST_UPDATE_COMPLETE: "清單已更新至最新版本"
		HELP_TITLE: "使用槍匠機器人t"
		HELP_TEXT: "為了展示您的項目，@ 機器人使用您的用戶名，類，網絡和項目槽，用空格分隔。\n如果沒有指定類，機器人將始終查看最近播放的課程。\n如果您已設置 您的鬆散配置文件，以便您的*名字*與您的用戶名匹配，您可以省略它。\n如果您的gamertag僅存在於一個網絡上，也可以省略。"
	